<?php /*
The Virtual Career Network (VCN) is an "open source, open content" workforce services and online learning delivery platform built and operated by the American Association of Community Colleges (AACC) under a grant from the Employment and Training Administration (ETA) of the United States Department of Labor (DOL).

Copyright (C) 2012 American Association of Community Colleges

This file is part of the source code for the Virtual Career Network.

The Virtual Career Network is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The Virtual Career Network is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/.
*/ ?>


<?php

/**
 * Implementation of hook_help().
 */
function vcntop10_help($path, $arg) {
	if ($path == 'admin/help#vcntop10') {
		return t('Functionality related to VCN Top 10 by jobs/Growth/Pay.');
  }
}

/**
 * Implementation of hook_preprocess().
 * /top10byjobs (Top 10 Most In Demand Healthcare Careers)
 */
function vcntop10_preprocess_vcn_top10_by_jobs_template(&$variables) {
	
	if (empty($variables['industry'])) {
		$variables['industry'] = vcn_get_industry();
	}	
  
  $variables['industry_name'] = vcn_get_industry_name();
  
	$variables['vcn_drupal7_base_path'] = vcn_drupal7_base_path();
	
	/* REST Call */	
	// get the list of occupation order by 'aopent' desc limit 10
	$params = array('industry' => $variables['industry'], 'limit' => '10' , 'order' => 'aopent' , 'direction' => 'desc'); // D6 param not added here. 'dl' => 'desc'
	$occupationlist = vcn_rest_wrapper('vcnoccupationsvc', 'vcncareer', 'get-career-list-by-jobs', $params);
	$variables["occupationlist"] = $occupationlist;
	/* End REST Call */
}

/**
 * Implementation of hook_preprocess().
 * /top10bygrowth (BY GROWTH NUMBER - Top 10 Fastest Growing Healthcare Careers)
 */
function vcntop10_preprocess_vcn_top10_by_growth_template(&$variables) {
	
	if (empty($variables['industry'])) {
		$variables['industry'] = vcn_get_industry();
	}
  
  $variables['industry_name'] = vcn_get_industry_name();
  
	$variables['vcn_drupal7_base_path'] = vcn_drupal7_base_path();
	
	/* REST Call */ 	
	// get the list of occupation order by 'pchg' desc limit 10
	$params = array('industry' => $variables['industry'], 'limit' => '10' , 'order' => 'pchg' , 'direction' => 'desc');
	$occupationlist = vcn_rest_wrapper('vcnoccupationsvc', 'vcncareer', 'get-career-list-by-growth', $params);
	$variables["occupationlist"] = $occupationlist;
	/* End REST Call */
}

/**
 * Implementation of hook_preprocess().
 * /top10bypay (BY MEDIAN WAGE - Top 10 Salaries for Healthcare Careers)
 */
function vcntop10_preprocess_vcn_top10_by_pay_template(&$variables) {
	
	if (empty($variables['industry'])) {
		$variables['industry'] = vcn_get_industry();
	}
  
  $variables['industry_name'] = vcn_get_industry_name();
  
	$variables['vcn_drupal7_base_path'] = vcn_drupal7_base_path();
	
	/* REST Call */ 	
	// Hard coded list is not added from d6 to D7
	//$onetcode= array('29-1071.00','29-2021.00','15-1121.01','29-1123.00','29-2035.00','29-2092.00','31-9091.00','31-2012.00','31-1015.00','31-1014.00');
	
	// get the list of occupation order by 'median' desc limit 10
	//$params = array('onetcode' => $onetcode , 'order' => 'median' , 'direction' => 'desc');
	$params = array('industry' => $variables['industry'], 'limit' => '10' , 'order' => 'median' , 'direction' => 'desc');
	$occupationlist = vcn_rest_wrapper('vcnoccupationsvc', 'vcncareer', 'get-career-list-by-pay', $params);
	$variables["occupationlist"] = $occupationlist;
  
  // get the wage period year so we can display it
  $variables['period_year'] = getWagePeriodYear();
    
	/* End REST Call */	
}