<?php /*
The Virtual Career Network (VCN) is an "open source, open content" workforce services and online learning delivery platform built and operated by the American Association of Community Colleges (AACC) under a grant from the Employment and Training Administration (ETA) of the United States Department of Labor (DOL).

Copyright (C) 2012 American Association of Community Colleges

This file is part of the source code for the Virtual Career Network.

The Virtual Career Network is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The Virtual Career Network is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/.
*/ ?>


<?php

/**
 * Implementation of hook_help().
 */
function vcneducationmatch_help($path, $arg) {
	if ($path == 'admin/help#vcneducationmatch') {
		return t('Functionality related to VCN Match Your Education to Careers.');
  }
}

/**
 * Implementation of hook_preprocess().
 * /educationmatch (Match Your Education to Careers)
 */
function vcneducationmatch_preprocess_vcn_education_match_template(&$variables) {
	
	if (empty($variables['industry'])) {
		$variables['industry'] = vcn_get_industry();
	}
	
	/* REST Call */
	
	// get the list of Occupation category list
	$params = array();
	$occupation_cat_list = vcn_rest_wrapper('vcnlookupsvc', 'vcnlookup', 'get-education-category', $params);
	$variables['occupation_cat_list'] = $occupation_cat_list->categories;
	
	if(isset($_POST["edu_current_select"]) && intval($_POST["edu_current_select"]) > 0) {
		$variables["edu_current"] = intval($_POST["edu_current_select"]);
	}else {
		$variables["edu_current"] = 1;
	}
	
	if(isset($_POST["edu_towards_select"]) && intval($_POST["edu_towards_select"]) > 0) {
		$variables["edu_towards"] = intval($_POST["edu_towards_select"]);
	}else {
		$variables["edu_towards"] ='1';
	}
	
	$params = array('industry' => $variables['industry'], 'mineducation' => $variables["edu_current"] , 'order' => 'display_title' , 'direction' => 'asc');
	$occupation_current_careers = vcn_rest_wrapper('vcnoccupationsvc', 'vcncareer', 'get-career-list-by-min-education', $params);
	$variables['occupation_current_careers'] = $occupation_current_careers;

	$params = array('industry' => $variables['industry'], 'mineducation' => $variables["edu_towards"] , 'order' => 'display_title' , 'direction' => 'asc');
	$occupation_towards_careers = vcn_rest_wrapper('vcnoccupationsvc', 'vcncareer', 'get-career-list-by-min-education', $params);
	$variables['occupation_towards_careers'] = $occupation_towards_careers;
	
	/* End REST Call */
	
	$path = drupal_get_path('theme', 'vcnstark');
	drupal_add_js($path . '/js/vcn_education_match.js');
	
	// Call fucntion to access the node containing editable text by "URL Alias" of specific node.
	$variables['hinttext'] = vcn_node_text_by_urlalias("match-education-hint");
}
