<?php /*
The Virtual Career Network (VCN) is an "open source, open content" workforce services and online learning delivery platform built and operated by the American Association of Community Colleges (AACC) under a grant from the Employment and Training Administration (ETA) of the United States Department of Labor (DOL).

Copyright (C) 2012 American Association of Community Colleges

This file is part of the source code for the Virtual Career Network.

The Virtual Career Network is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The Virtual Career Network is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/.
*/ ?>


<?php

/**
 * Implementation of hook_help().
 */
function vcncareerladder_help($path, $arg) {
	if ($path == 'admin/help#vcncareerladder') {
		return t('Functionality related to VCN Career Pathway.');
  }
}

/**
 * Implementation of hook_preprocess().
 * /careerladder/onetcode/% (Career Pathway by onetcode)
 */
function vcncareerladder_preprocess_vcn_career_ladder_by_onetcode_template(&$variables) {

	// Call fucntion to access the node containing editable text by "URL Alias" of specific node.
	$variables['career_pathway_note'] = vcn_node_text_by_urlalias("careerladder-byonet-text");

}

/**
 * Implementation of hook_preprocess().
 * /careerladder/% (Career Pathway by worktype code)
 */
function vcncareerladder_preprocess_vcn_career_ladder_by_worktype_template(&$variables) {	

}