<?php /*
The Virtual Career Network (VCN) is an "open source, open content" workforce services and online learning delivery platform built and operated by the American Association of Community Colleges (AACC) under a grant from the Employment and Training Administration (ETA) of the United States Department of Labor (DOL).

Copyright (C) 2012 American Association of Community Colleges

This file is part of the source code for the Virtual Career Network.

The Virtual Career Network is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The Virtual Career Network is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/.
*/ ?>


<?php

/**
 * Implementation of hook_help()
 */
function vcnfooter_help($path, $arg) {
  if ($path == 'admin/help#vcnfooter') {
    return t('Footer block for VCN.');
  }
}

/**
 * Implementation of hook_block_info()
 */
function vcnfooter_block_info() {
  $blocks = array();
  $blocks['main'] = array(
    'info' => t('Main Footer Block'),
  );
  $blocks['healthcare'] = array(
  		'info' => t('Healthcare Footer Block'),
  );
  $blocks['igen'] = array(
  		'info' => t('IGEN Footer Block'),
  );
  $blocks['transit'] = array(
  		'info' => t('Transit Footer Block'),
  );
  $blocks['aarp'] = array(
  		'info' => t('AARP Footer Block'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view()
 */
function vcnfooter_block_view($delta='') {
  $block = array();

  switch($delta) {
     case 'main':
        $block['content'] = theme('vcnfooter_block');
        break;
     case 'healthcare':
        $block['content'] = theme('vcnfooter_healthcare_block');
        break;
     case 'igen':
        $block['content'] = theme('vcnfooter_igen_block');
        break;   
     case 'transit':
        $block['content'] = theme('vcnfooter_transit_block');
        break;
     case 'aarp':
        $block['content'] = theme('vcnfooter_aarp_block');
        break;
  }

  return $block;
}

/**
 * Implementation of hook_theme()
 */
function vcnfooter_theme() {
  $theme = array();
  
  $theme['vcnfooter_block'] = array(
	   'variables' => array(),
	  'template' => 'vcnfooter-block',  	  
  );
  
  $theme['vcnfooter_healthcare_block'] = array(
  		'variables' => array(),
  		'template' => 'vcnfooter-healthcare-block',  		
  );
  
  $theme['vcnfooter_igen_block'] = array(
  	 	'variables' => array(),
  		'template' => 'vcnfooter-igen-block',  		
  );
  
  $theme['vcnfooter_transit_block'] = array(
  	 	'variables' => array(),
  		'template' => 'vcnfooter-transit-block',  		
  );
  
  $theme['vcnfooter_aarp_block'] = array(
  	 	'variables' => array(),
  		'template' => 'vcnfooter-aarp-block',  		
  );
  
  return $theme;
}

/**
 * Implementation of hook_preprocess_HOOK()
 */

function vcnfooter_preprocess_vcnfooter_block(&$variables) {	

	$subsite = vcn_determine_vcn_subsite();	
	$industry_code =  vcn_get_industry_code();		
	
	$block = module_invoke('vcnfooter', 'block_view', $industry_code);
	$variables['footer_content'] = render($block['content']);	
	
}

function vcnfooter_preprocess_vcnfooter_healthcare_block(&$variables) {
	$variables['vcn_drupal7_base_path'] = vcn_drupal7_base_path();
}

function vcnfooter_preprocess_vcnfooter_igen_block(&$variables) {
	$variables['vcn_drupal7_base_path'] = vcn_drupal7_base_path();
}

function vcnfooter_preprocess_vcnfooter_transit_block(&$variables) {
	$variables['vcn_drupal7_base_path'] = vcn_drupal7_base_path();
}

function vcnfooter_preprocess_vcnfooter_aarp_block(&$variables) {
	$variables['vcn_drupal7_base_path'] = vcn_drupal7_base_path();
}
